### ISSUE TITLE
Signed In User Profile

### ISSUE THREAD

**Issue by naszifnaaz** [RationalPrabal/Baby-Bliss#45]
The signed in user profile is hardcoded and the styling does not match with the rest of the website. This requires a revamp and the data should be rendered dynamically.

**Comment by RationalPrabal** [comment]
![Screenshot_20230127_162033](https://user-images.githubusercontent.com/108731705/222383983-e1508993-2073-45f6-abdf-98247f5a4502.png)
Are you talking about this page?
